# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yPFiTp1Hsj3TUSQ3PKBKF6bWvZS3H7Jb
"""

import requests
from bs4 import BeautifulSoup


url = 'https://www.imdb.com/chart/top/'
page = requests.get(url)

soup = BeautifulSoup(page.content, "html.parser")
soup.title= "IMDB Rating"
for link in soup.find_all('a'):
    print(link.get('href'))